In [10]:
import tensorflow as tf

random_scalar = tf.random_uniform(())
sess = tf.Session()
sess.run(random_scalar)




In [14]:
double_random_scalar = 2 * random_scalar
double_random_scalar_gt_one = double_random_scalar > 1

sess.run(double_random_scalar_gt_one)

True

In [15]:
np.random.rand(2,3)

array([[ 0.84846682,  0.07957784,  0.09947537],
       [ 0.23025143,  0.86254493,  0.25724576]])

In [16]:
random_tensor = tf.random_uniform((2,3))
double_random_tensor = 2 * random_tensor
double_random_tensor_gt_one = double_random_tensor > 1
sess.run(double_random_tensor_gt_one)

array([[ True, False, False],
       [ True,  True,  True]], dtype=bool)

In [30]:
def np_fn(x):
    mu=0
    sigma=1
    exp=np.e ** ( -(((x-mu)**2) / (2*sigma**2)))
    rslt=(1 / np.sqrt(2 * sigma**2 * np.pi)) * exp
    print(rslt)
    
x = np.array([0, 1, 2, 3])
np_fn(x)




[ 0.39894228  0.24197072  0.05399097  0.00443185]


In [34]:
import tensorflow as tf
import numpy as np

def tf_fn(x):
    mu=0
    sigma=1
    
    x1 = tf.placeholder(tf.float32, [None])
    exp=tf.exp(-((tf.subtract(x1,mu)**2) / (2*sigma**2)))
    rslt = tf.rsqrt(2 * sigma**2 * np.pi)*exp

    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    rslt2 = sess.run(rslt, {x1: x})
    return rslt2

x = np.array([0, 1, 2, 3])
tf_fn(x)

array([ 0.39894229,  0.24197073,  0.05399097,  0.00443185], dtype=float32)